from src.processDat import processDat
from pathlib import Path
BCI2kPath = Path("C:\BCI2000.x64\data")
dataPath = BCI2kPath / "NoahTesting000" /"NoahTestingS000R24.dat"
t = processDat(dataPath,notchOrder = 2, commonRef=False)
# t.plotStimOn()
# t.generateTriggerChannel()
t.build_MNE_Epochs(plotEpochs=True)
# t.plotEvokedTopo()
# t.plotEvokedPSD()
# t.eyetracking.plotAttr('Size',dec='Smooth')
# t.eyetracking.plotAttr('Size',smooth=False)
# t.eyetracking.plotAllAttr(subplot=True)
# t.build_MNE_Epochs()
# t.VisualizeRawOffset()
# t.plotEpochs()
# t.plotEpochsSubplot()
# t.whole_block_psds()
# t.epochFFT()
# t.plotStimulusCode()
# t.plotAllStates()
# t.plotPowerBands_oneChannel(10)
t.show()